[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools>=61.2",
]

[project]
name = "sc2reader"
description = "Utility for parsing Starcraft II replay files"
keywords = [
  "parser",
  "replay",
  "sc2",
  "starcraft 2",
]
license = { text = "MIT" }
authors = [ { name = "Kevin Leung", email = "kkleung89@gmail.com" } ]
requires-python = ">=3.9"
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
  "Topic :: Games/Entertainment",
  "Topic :: Games/Entertainment :: Real Time Strategy",
  "Topic :: Software Development",
  "Topic :: Software Development :: Libraries",
  "Topic :: Utilities",
]
dynamic = [
  "readme",
  "version",
]
dependencies = [
  "mpyq",
  "pillow",
]
optional-dependencies.testing = [
  "pytest",
]
urls.Homepage = "https://github.com/ggtracker/sc2reader"
scripts.sc2attributes = "sc2reader.scripts.sc2attributes:main"
scripts.sc2json = "sc2reader.scripts.sc2json:main"
scripts.sc2parse = "sc2reader.scripts.sc2parse:main"
scripts.sc2printer = "sc2reader.scripts.sc2printer:main"
scripts.sc2replayer = "sc2reader.scripts.sc2replayer:main"

[tool.setuptools]
include-package-data = true
zip-safe = true
platforms = [ "any" ]
dynamic.readme = { file = [ "README.rst", "CHANGELOG.rst" ] }
dynamic.version = { attr = "sc2reader.__version__" }
packages.find = { namespaces = false }

[tool.ruff]
line-length = 129
lint.ignore = [
  "F401", # module imported but unused; consider using `importlib.util.find_spec` to test for availability
  "F403", # Run `removestar` on this codebase
  "F405", # Run `removestar` on this codebase
  "F841", # Run `ruff --select=F841 --fix .`
]
lint.mccabe.max-complexity = 34

[tool.codespell]
ignore-words-list = "queenland"
