version: 2.1

jobs:
  pre-commit:
    docker:
      - image: cimg/python:3.14
    steps:
      - checkout
      # pipx is already installed, but `pipx list` is empty
      - run: python --version ; pip --version ; pipx --version ; pwd ; ls -l
      - run: pipx run pre-commit run --all-files --show-diff-on-failure

  pytest:
    docker:
      - image: cimg/python:3.14
    steps:
      - checkout
      - run: pip install pytest -r requirements.txt
      - run: pip install --editable .
      - run: pytest

workflows:
  build:
    jobs:
      - pre-commit
      - pytest
