version: 2.1

build_and_test: &build_and_test_steps
  - checkout
  # Do not use `sudo pip`
  # pipx is already installed, but `pipx list` is empty
  - run: python --version ; pip --version ; pipx --version ; pwd ; ls -l
  - run: pip install pytest -r requirements.txt
  - run: pip install --editable .
  - run: pytest


jobs:
  StyleCheck:
    docker:
      - image: cimg/python:3.14
    steps:
      - checkout
      - run: python --version ; pip --version ; pipx --version ; pwd ; ls -l
      - run: pipx run codespell -L queenland,uint,assertin
      - run: pipx run ruff check
      - run: pipx run black . --check


  Python3:
    docker:
      - image: cimg/python:3.14
    steps: *build_and_test_steps


workflows:
  build:
    jobs:
      - StyleCheck
      - Python3
