# https://circleci.com/developer/orbs/orb/circleci/python#usage-work-with-uv

version: '2.1'
orbs:
  python: circleci/python@4.0.0

jobs:
  pre-commit:
    # executor:
    #  name: python/default
    #  tag: "3.14"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: uv
      - run:
          command: |
            uvx pre-commit run --all-files --show-diff-on-failure

  pytest:
    # executor:
    #  name: python/default
    #  tag: "3.14"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: uv
      - run:
          command: |
            uv venv --allow-existing
            pip install --editable ".[testing]"
            pytest

workflows:
  main:
    jobs:
      - pre-commit
      - pytest
